#spring:
#  data:
#    cassandra:
#      port: 9042
#      contact-points: 127.0.0.1
#      keyspace-name: weatherspace
#      schema-action: create_if_not_exists
#      entity-base-package: pl.nosql.weather.cityweatherapp.model
#      local-datacenter: datacenter1