package pl.nosql.weather.cityweatherapp.service;

import org.springframework.beans.factory.annotation.Autowired;
import pl.nosql.weather.cityweatherapp.model.WeatherData;
import pl.nosql.weather.cityweatherapp.repository.WeatherRepository;

import java.util.Date;
import java.util.List;

@org.springframework.stereotype.Service
public class Service {
    private final WeatherRepository weatherRepository;

    @Autowired
    public Service(WeatherRepository weatherRepository) {
        this.weatherRepository = weatherRepository;
    }

    //TODO methods generated by IDEA, need refactor


    public List<WeatherData> findAll() {
        return weatherRepository.findAll();
    }

    public <S extends WeatherData> S saveData(S entity) { //
        return weatherRepository.save(entity);
    }

    public WeatherData getById(int id) {
        return weatherRepository.getById(id);
    }

    public void deleteById(int id) {
        weatherRepository.deleteById(id);
    }

    public List<WeatherData> getByFindName(String findName) {
        return weatherRepository.getByFindName(findName);
    }

    public List<WeatherData> getByCityId(int cityId) {
        return weatherRepository.getByCityId(cityId);
    }

    public List<WeatherData> getByCityIdAndTimeBetween(int cityId, Date dateStart, Date dateEnd) {
        return weatherRepository.getByCityIdAndTimeBetween(cityId, dateStart, dateEnd);
    }
}
