version: '3'
services:
  mycassandra:
    image: cassandra
    container_name: mycassandra
    ports:
    - "9042:9042"

#  springbootapp:
#    ports:
#    - "8080:8080"
#    environment:
#      CASSANDRA_CONTACTPOINTS: 127.0.0.1
#      CASSANDRA_PORT: 7000
#    build:
#      context: .
#      args:
#        JAR_FILE: /CityWeatherApp-0.0.1-SNAPSHOT.jar
#    restart: always